version: "3.3"

services:

  telicent-jena-smart-cache:
    command:
      - --config
      - /fuseki/config/config.ttl
    environment:
      ADMIN_PASSWORD: password
    image: 098669589541.dkr.ecr.eu-west-2.amazonaws.com/smart-cache-graph:0.60.1
    ports:
      - mode: ingress
        target: 3030
        published: "3030"
        protocol: tcp
    volumes:
      - ./volume:/fuseki/config:ro
      - ./data:/fuseki/data:ro
