name: Publish new release version

permissions:
  contents: write
  pull-requests: write

on:
  push:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          prerelease: true
          config-path: .github/release-please-config.json
