name: Publish new release version

on:
  push:
    branches:
      - "main"

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          prerelease: true
          config-path: .github/release-please-config.json
