name: Publish release candidate
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: | 
          git checkout ${GITHUB_REF#refs/heads/}
          pnpm install
          pnpm dlx nx run-many -t test,build -p @telicent-io/rdfservice @telicent-io/ontologyservice 
          pnpm dlx nx release publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN }}
